version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    #depends_on:
    #  - database

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: personel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
volumes:
  db_data:
